### ISSUE TITLE
Containerizing the project and implementing workflows

### ISSUE THREAD

**Issue by JesseStorms** [afstudeerprojecten/FeedbackAI-Tool-Backend#8]
Title; we're lazy and we want to get GitHub to automatically build and push our containers somewhere.

This is a subtask from afstudeerprojecten/project2024-meta#16. 

## Tasks

- [x] Containerize the project
- [ ] Write workflow to build master
- [x] Write workflow to build staging (e.g canary)
